// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.12.4
// source: example/udemy/chatapplication/chat_grpc/proto_file.proto

package chat_proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// ChatServiceClient is the client API for ChatService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ChatServiceClient interface {
	ReqJoinChat(ctx context.Context, in *Client, opts ...grpc.CallOption) (*ResponseJoinReq, error)
	ClientChat(ctx context.Context, opts ...grpc.CallOption) (ChatService_ClientChatClient, error)
	ServerChat(ctx context.Context, in *Client, opts ...grpc.CallOption) (ChatService_ServerChatClient, error)
}

type chatServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewChatServiceClient(cc grpc.ClientConnInterface) ChatServiceClient {
	return &chatServiceClient{cc}
}

func (c *chatServiceClient) ReqJoinChat(ctx context.Context, in *Client, opts ...grpc.CallOption) (*ResponseJoinReq, error) {
	out := new(ResponseJoinReq)
	err := c.cc.Invoke(ctx, "/ChatService/ReqJoinChat", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *chatServiceClient) ClientChat(ctx context.Context, opts ...grpc.CallOption) (ChatService_ClientChatClient, error) {
	stream, err := c.cc.NewStream(ctx, &ChatService_ServiceDesc.Streams[0], "/ChatService/ClientChat", opts...)
	if err != nil {
		return nil, err
	}
	x := &chatServiceClientChatClient{stream}
	return x, nil
}

type ChatService_ClientChatClient interface {
	Send(*ClientMessage) error
	CloseAndRecv() (*Client, error)
	grpc.ClientStream
}

type chatServiceClientChatClient struct {
	grpc.ClientStream
}

func (x *chatServiceClientChatClient) Send(m *ClientMessage) error {
	return x.ClientStream.SendMsg(m)
}

func (x *chatServiceClientChatClient) CloseAndRecv() (*Client, error) {
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	m := new(Client)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *chatServiceClient) ServerChat(ctx context.Context, in *Client, opts ...grpc.CallOption) (ChatService_ServerChatClient, error) {
	stream, err := c.cc.NewStream(ctx, &ChatService_ServiceDesc.Streams[1], "/ChatService/ServerChat", opts...)
	if err != nil {
		return nil, err
	}
	x := &chatServiceServerChatClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type ChatService_ServerChatClient interface {
	Recv() (*ClientMessage, error)
	grpc.ClientStream
}

type chatServiceServerChatClient struct {
	grpc.ClientStream
}

func (x *chatServiceServerChatClient) Recv() (*ClientMessage, error) {
	m := new(ClientMessage)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// ChatServiceServer is the server API for ChatService service.
// All implementations must embed UnimplementedChatServiceServer
// for forward compatibility
type ChatServiceServer interface {
	ReqJoinChat(context.Context, *Client) (*ResponseJoinReq, error)
	ClientChat(ChatService_ClientChatServer) error
	ServerChat(*Client, ChatService_ServerChatServer) error
	mustEmbedUnimplementedChatServiceServer()
}

// UnimplementedChatServiceServer must be embedded to have forward compatible implementations.
type UnimplementedChatServiceServer struct {
}

func (UnimplementedChatServiceServer) ReqJoinChat(context.Context, *Client) (*ResponseJoinReq, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ReqJoinChat not implemented")
}
func (UnimplementedChatServiceServer) ClientChat(ChatService_ClientChatServer) error {
	return status.Errorf(codes.Unimplemented, "method ClientChat not implemented")
}
func (UnimplementedChatServiceServer) ServerChat(*Client, ChatService_ServerChatServer) error {
	return status.Errorf(codes.Unimplemented, "method ServerChat not implemented")
}
func (UnimplementedChatServiceServer) mustEmbedUnimplementedChatServiceServer() {}

// UnsafeChatServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ChatServiceServer will
// result in compilation errors.
type UnsafeChatServiceServer interface {
	mustEmbedUnimplementedChatServiceServer()
}

func RegisterChatServiceServer(s grpc.ServiceRegistrar, srv ChatServiceServer) {
	s.RegisterService(&ChatService_ServiceDesc, srv)
}

func _ChatService_ReqJoinChat_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Client)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChatServiceServer).ReqJoinChat(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ChatService/ReqJoinChat",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChatServiceServer).ReqJoinChat(ctx, req.(*Client))
	}
	return interceptor(ctx, in, info, handler)
}

func _ChatService_ClientChat_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(ChatServiceServer).ClientChat(&chatServiceClientChatServer{stream})
}

type ChatService_ClientChatServer interface {
	SendAndClose(*Client) error
	Recv() (*ClientMessage, error)
	grpc.ServerStream
}

type chatServiceClientChatServer struct {
	grpc.ServerStream
}

func (x *chatServiceClientChatServer) SendAndClose(m *Client) error {
	return x.ServerStream.SendMsg(m)
}

func (x *chatServiceClientChatServer) Recv() (*ClientMessage, error) {
	m := new(ClientMessage)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func _ChatService_ServerChat_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(Client)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(ChatServiceServer).ServerChat(m, &chatServiceServerChatServer{stream})
}

type ChatService_ServerChatServer interface {
	Send(*ClientMessage) error
	grpc.ServerStream
}

type chatServiceServerChatServer struct {
	grpc.ServerStream
}

func (x *chatServiceServerChatServer) Send(m *ClientMessage) error {
	return x.ServerStream.SendMsg(m)
}

// ChatService_ServiceDesc is the grpc.ServiceDesc for ChatService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ChatService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "ChatService",
	HandlerType: (*ChatServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ReqJoinChat",
			Handler:    _ChatService_ReqJoinChat_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "ClientChat",
			Handler:       _ChatService_ClientChat_Handler,
			ClientStreams: true,
		},
		{
			StreamName:    "ServerChat",
			Handler:       _ChatService_ServerChat_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "example/udemy/chatapplication/chat_grpc/proto_file.proto",
}
